### PR TITLE
lazy loading has been completed for all routes.

### PR DESCRIPTION
**Pull request by anantrajjj**
Fixes #
Issue:-
Update the file [app.router.ts](https://github.com/despensa-app/despensa-web/blob/ed142000efab1210e38f7999b9028d96032122f8/src/app/app.routes.ts) to change the component fields of the routes to loadComponent.

**Description**
 [app.router.ts]The  component fields of the routes to loadComponent has been done.

**Screenshots**
image

### CODE REVIEW

**Comment by nmarulo** [comment]
@anantrajjj Please read issue #2 first.

I don't know if the PR is for hacktoberfes. If not, it's ok.

Thanks for your interest.

**Comment by anantrajjj** [comment]
I just wanted to prepare for the actual hacktoberfest before the real thing, can it be considered for it too?

**Comment by anantrajjj** [comment]
I wanted to prepare for the hacktoberfest beforehand, so i tried this project . If it could be considered for hacktoberfest, could you please review and merge if it meets the requirement.

**Comment by nmarulo** [comment]
@anantrajjj 
I understand, but in the incident I mentioned earlier, I indicated that please wait for the incidents to be assigned before creating them and also in this case, for the event, not to create them ahead of time.

And if I check the PR and it seems correct. But you have to comment on the incident so that it can be assigned to you.

Tomorrow I will open the incidents. 

I will try to create more and make them easy to help everyone.

**Pull request closed without merging**
